name: Whitesource Unified Agent Scan - .NET (dotnet)

on: [push, pull_request, workflow_dispatch]

jobs:

  build:
    env:
      WS_ProductionBranches: "main,release"
      WS_DevKey: "e9325f5150604d60a5a5843e6155b65eb4c6ff62b16847c2895da8de40747c40"
      WS_Contains: "${GITHUB_REF_NAME}"
      
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: WhiteSource Unified Agent Scan
      run: |
        echo "WS_Contains "$WS_Contains
        echo "GITHUB_REF_NAME = "${GITHUB_REF_NAME}
        
      
    - name: Set Org API Key
      if:   contains('Hello main world', '$WS_Contains')
      run:  echo "Woo Ho!"
     
    - name: Set Org API Key2
      if:   contains('main,release', 'main')
      run:  echo "Woo Ho 2!"
     
      
